# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chunk_pb2 as chunk__pb2


class FileServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.upload = channel.stream_unary(
                '/FileServer/upload',
                request_serializer=chunk__pb2.Chunk.SerializeToString,
                response_deserializer=chunk__pb2.Reply.FromString,
                )
        self.alive = channel.unary_unary(
                '/FileServer/alive',
                request_serializer=chunk__pb2.Alive.SerializeToString,
                response_deserializer=chunk__pb2.Alive.FromString,
                )
        self.alive_stream = channel.unary_stream(
                '/FileServer/alive_stream',
                request_serializer=chunk__pb2.Alive.SerializeToString,
                response_deserializer=chunk__pb2.Detection.FromString,
                )
        self.download = channel.unary_stream(
                '/FileServer/download',
                request_serializer=chunk__pb2.Request.SerializeToString,
                response_deserializer=chunk__pb2.Chunk.FromString,
                )
        self.download_detection = channel.unary_unary(
                '/FileServer/download_detection',
                request_serializer=chunk__pb2.Request.SerializeToString,
                response_deserializer=chunk__pb2.Detection.FromString,
                )
        self.get_box = channel.unary_stream(
                '/FileServer/get_box',
                request_serializer=chunk__pb2.Request.SerializeToString,
                response_deserializer=chunk__pb2.Detection.FromString,
                )


class FileServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def alive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def alive_stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def download_detection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_box(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'upload': grpc.stream_unary_rpc_method_handler(
                    servicer.upload,
                    request_deserializer=chunk__pb2.Chunk.FromString,
                    response_serializer=chunk__pb2.Reply.SerializeToString,
            ),
            'alive': grpc.unary_unary_rpc_method_handler(
                    servicer.alive,
                    request_deserializer=chunk__pb2.Alive.FromString,
                    response_serializer=chunk__pb2.Alive.SerializeToString,
            ),
            'alive_stream': grpc.unary_stream_rpc_method_handler(
                    servicer.alive_stream,
                    request_deserializer=chunk__pb2.Alive.FromString,
                    response_serializer=chunk__pb2.Detection.SerializeToString,
            ),
            'download': grpc.unary_stream_rpc_method_handler(
                    servicer.download,
                    request_deserializer=chunk__pb2.Request.FromString,
                    response_serializer=chunk__pb2.Chunk.SerializeToString,
            ),
            'download_detection': grpc.unary_unary_rpc_method_handler(
                    servicer.download_detection,
                    request_deserializer=chunk__pb2.Request.FromString,
                    response_serializer=chunk__pb2.Detection.SerializeToString,
            ),
            'get_box': grpc.unary_stream_rpc_method_handler(
                    servicer.get_box,
                    request_deserializer=chunk__pb2.Request.FromString,
                    response_serializer=chunk__pb2.Detection.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FileServer/upload',
            chunk__pb2.Chunk.SerializeToString,
            chunk__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def alive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileServer/alive',
            chunk__pb2.Alive.SerializeToString,
            chunk__pb2.Alive.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def alive_stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileServer/alive_stream',
            chunk__pb2.Alive.SerializeToString,
            chunk__pb2.Detection.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileServer/download',
            chunk__pb2.Request.SerializeToString,
            chunk__pb2.Chunk.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def download_detection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileServer/download_detection',
            chunk__pb2.Request.SerializeToString,
            chunk__pb2.Detection.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_box(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileServer/get_box',
            chunk__pb2.Request.SerializeToString,
            chunk__pb2.Detection.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
